//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HydroAsp.LocalResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HydroAsp.LocalResource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgarian.
        /// </summary>
        public static string Bg {
            get {
                return ResourceManager.GetString("Bg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHECK THE CONDITIONS.
        /// </summary>
        public static string CheckConditions {
            get {
                return ResourceManager.GetString("CheckConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions.
        /// </summary>
        public static string Conditions {
            get {
                return ResourceManager.GetString("Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONNECT THE UNEXPECTED.
        /// </summary>
        public static string ConnectTheUnexpected {
            get {
                return ResourceManager.GetString("ConnectTheUnexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DON&apos;T LET THEM TELL YOU WHAT IS THE BEST A MAN CAN GET - CHOOSE YOURSELF!.
        /// </summary>
        public static string DoNotLet {
            get {
                return ResourceManager.GetString("DoNotLet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string En {
            get {
                return ResourceManager.GetString("En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIND OUT HOW TO GET YOUR FREE SAMPLE BELOW..
        /// </summary>
        public static string FindSample {
            get {
                return ResourceManager.GetString("FindSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FITS FUSION®† HANDLES**.
        /// </summary>
        public static string FitsFusionHandle {
            get {
                return ResourceManager.GetString("FitsFusionHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you know that the new Wilkinson Sword Hydro Connect™ 5 cartridge is compatible with all Fusion®† and Wilkinson Sword Hydro Connect™ 5 branded handles? This gives you the freedom to choose what blades to use with your preffered razor before you decide to change it..
        /// </summary>
        public static string HeaderText1 {
            get {
                return ResourceManager.GetString("HeaderText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now we give you the opportunity to receive a FREE SAMPLE so you can test all the benefits of Wilkinson Sword Hydro Connect™ 5 blades on your own skin!.
        /// </summary>
        public static string HeaderText2 {
            get {
                return ResourceManager.GetString("HeaderText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade to GEL HYDRATION.
        /// </summary>
        public static string HidratePart1 {
            get {
                return ResourceManager.GetString("HidratePart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to hydrate skin throughout each shave.
        /// </summary>
        public static string HidratePart2 {
            get {
                return ResourceManager.GetString("HidratePart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        public static string Sample {
            get {
                return ResourceManager.GetString("Sample", resourceCulture);
            }
        }
    }
}
